const PRODUCTS = [
    {
        nome: "SS 1530 MF W",
        tipo: "controlador",
        capacidade: 3000,
        auth: ["Face", "Senha", "Tag", "QRcode"],
        com: ["RS 485", "Wiegand"],
        grauIP: "N/A",
        freq: 13.56,
        rede: ["Ethernet", "wi-fi"],
        fornecedor: "Dahua"
    },
    {
        nome: "SS 1540 MF W",
        tipo: "controlador",
        capacidade: 3000,
        auth: ["Face", "Senha", "Tag", "QRcode", "Biometria"],
        com: ["RS 485", "Wiegand"],
        grauIP: "N/A",
        freq: 13.56,
        rede: ["Ethernet", "wi-fi"],
        fornecedor: "Dahua"
    },
    {
        nome: "SS 3420 MF Bio",
        tipo: "controlador",
        capacidade: 30000,
        auth: ["Tag", "Biometria"],
        com: ["RS 485", "Wiegand"],
        grauIP: "IP65",
        freq: 13.56,
        rede: ["Ethernet"],
        fornecedor: "Dahua"
    },
    {
        nome: "SS 3420 Bio",
        tipo: "controlador",
        capacidade: 30000,
        auth: ["Tag", "Biometria"],
        com: ["RS 485", "Wiegand"],
        grauIP: "IP65",
        freq: 125,
        rede: ["Ethernet"],
        fornecedor: "Dahua"
    },
    {
        nome: "SS 3430 MF Bio",
        tipo: "controlador",
        capacidade: 30000,
        auth: ["Tag", "Biometria", "Senha"],
        com: ["RS 485", "Wiegand"],
        grauIP: "N/A",
        freq: 13.56,
        rede: ["Ethernet", "wi-fi"],
        fornecedor: "Dahua"
    },
    {
        nome: "SS 3430 Bio",
        tipo: "controlador",
        capacidade: 30000,
        auth: ["Tag", "Biometria", "Senha"],
        com: ["RS 485", "Wiegand"],
        grauIP: "N/A",
        freq: 125,
        rede: ["Ethernet", "wi-fi"],
        fornecedor: "Dahua"
    },
    {
        nome: "SS 3530 MF Face",
        tipo: "controlador",
        capacidade: 1500,
        auth: ["Face", "Senha", "Tag", "QRcode"],
        com: ["RS 485"],
        grauIP: "N/A",
        freq: 13.56,
        rede: ["Ethernet"],
        fornecedor: "Dahua"
    },
    {
        nome: "SS 3530 MF Face W",
        tipo: "controlador",
        capacidade: 1500,
        auth: ["Face", "Senha", "Tag", "QRcode"],
        com: ["RS 485"],
        grauIP: "N/A",
        freq: 13.56,
        rede: ["Ethernet", "wi-fi"],
        fornecedor: "Dahua"
    },
    {
        nome: "SS 3540 MF Face EX",
        tipo: "controlador",
        capacidade: 6000,
        auth: ["Face", "Senha", "Tag", "QRcode"],
        com: ["RS 485", "Wiegand"],
        grauIP: "IP65",
        freq: 13.56,
        rede: ["Ethernet", "wi-fi"],
        fornecedor: "Dahua"
    },
    {
        nome: "SS 3540 MF Face Bio EX",
        tipo: "controlador",
        capacidade: 6000,
        auth: ["Face", "Senha", "Tag", "QRcode", "Biometria"],
        com: ["RS 485", "Wiegand"],
        grauIP: "IP55",
        freq: 13.56,
        rede: ["Ethernet", "wi-fi"],
        fornecedor: "Dahua"
    },
    {
        nome: "SS 3532 MF W",
        tipo: "controlador",
        capacidade: 10000,
        auth: ["Face", "Senha", "Tag", "QRcode"],
        com: ["RS 485", "Wiegand"],
        grauIP: "IP55",
        freq: 13.56,
        rede: ["POE", "Ethernet", "wi-fi"],
        fornecedor: "Dahua"
    },
    {
        nome: "SS 3542 MF W",
        tipo: "controlador",
        capacidade: 10000,
        auth: ["Face", "Senha", "Tag", "QRcode", "Biometria"],
        com: ["RS 485", "Wiegand"],
        grauIP: "IP55",
        freq: 13.56,
        rede: ["POE", "Ethernet", "wi-fi"],
        fornecedor: "Dahua"
    },
    {
        nome: "SS 3532 MF",
        tipo: "controlador",
        capacidade: 10000,
        auth: ["Face", "Senha", "Tag", "QRcode"],
        com: ["RS 485", "Wiegand"],
        grauIP: "IP55",
        freq: 13.56,
        rede: ["Ethernet"],
        fornecedor: "Dahua"
    },
    {
        nome: "SS 3542 MF",
        tipo: "controlador",
        capacidade: 10000,
        auth: ["Face", "Senha", "Tag", "QRcode", "Biometria"],
        com: ["RS 485", "Wiegand"],
        grauIP: "IP55",
        freq: 13.56,
        rede: ["Ethernet"],
        fornecedor: "Dahua"
    },
    {
        nome: "SS 5530 MF Face",
        tipo: "controlador",
        capacidade: 50000,
        auth: ["Face", "Senha", "Tag", "QRcode"],
        com: ["RS 485", "Wiegand"],
        grauIP: "IP64",
        freq: 13.56,
        rede: ["Ethernet"],
        fornecedor: "Dahua"
    },
    {
        nome: "SS 5530 MF Face Lite",
        tipo: "controlador",
        capacidade: 20000,
        auth: ["Face", "Senha", "Tag", "QRcode"],
        com: ["RS 485", "Wiegand"],
        grauIP: "IP64",
        freq: 13.56,
        rede: ["Ethernet"],
        fornecedor: "Dahua"
    },
    {
        nome: "SS 5531 MF W",
        tipo: "controlador",
        capacidade: 20000,
        auth: ["Face", "Senha", "Tag", "QRcode"],
        com: ["RS 485", "Wiegand"],
        grauIP: "N/A",
        freq: 13.56,
        rede: ["Ethernet", "wi-fi"],
        fornecedor: "Dahua"
    },
    {
        nome: "SS 5532 MF W",
        tipo: "controlador",
        capacidade: 20000,
        auth: ["Face", "Senha", "Tag", "QRcode"],
        com: ["RS 485", "Wiegand"],
        grauIP: "IP55",
        freq: 13.56,
        rede: ["Ethernet", "wi-fi"],
        fornecedor: "Dahua"
    },
    {
        nome: "SS 5541 MF W",
        tipo: "controlador",
        capacidade: 20000,
        auth: ["Face", "Senha", "Tag", "QRcode", "Biometria"],
        com: ["RS 485", "Wiegand"],
        grauIP: "N/A",
        freq: 13.56,
        rede: ["Ethernet", "wi-fi"],
        fornecedor: "Dahua"
    },
    {
        nome: "SS 5542 MF W",
        tipo: "controlador",
        capacidade: 20000,
        auth: ["Face", "Senha", "Tag", "QRcode", "Biometria"],
        com: ["RS 485", "Wiegand"],
        grauIP: "IP55",
        freq: 13.56,
        rede: ["Ethernet", "wi-fi"],
        fornecedor: "Dahua"
    },
    {
        nome: "SS 120",
        tipo: "controlador",
        capacidade: 5000,
        auth: ["Tag"],
        com: ["Wiegand"],
        grauIP: "N/A",
        freq: 125,
        rede: ["Ethernet"],
        fornecedor: "ZKteco"
    },
    {
        nome: "SS 210",
        tipo: "controlador",
        capacidade: 30000,
        auth: ["Tag", "Senha"],
        com: ["RS 485", "Wiegand", "RS232"],
        grauIP: "N/A",
        freq: 125,
        rede: ["Ethernet"],
        fornecedor: "ZKteco"
    },
    {
        nome: "SS 230",
        tipo: "controlador",
        capacidade: 30000,
        auth: ["Tag", "Senha"],
        com: ["RS 485", "Wiegand", "RS232"],
        grauIP: "N/A",
        freq: 125,
        rede: ["Ethernet"],
        fornecedor: "ZKteco"
    },
    {
        nome: "SS 310",
        tipo: "controlador",
        capacidade: 200,
        auth: ["Tag", "Biometria"],
        com: ["RS 485", "Wiegand", "RS232"],
        grauIP: "N/A",
        freq: 125,
        rede: ["Ethernet"],
        fornecedor: "ZKteco"
    },
    {
        nome: "SS 311 E",
        tipo: "controlador",
        capacidade: 10000,
        auth: ["Tag", "Biometria"],
        com: ["RS 485", "Wiegand"],
        grauIP: "IP66",
        freq: 125,
        rede: ["Ethernet"],
        fornecedor: "ZKteco"
    },
    {
        nome: "SS 311 MF",
        tipo: "controlador",
        capacidade: 10000,
        auth: ["Tag", "Biometria"],
        com: ["RS 485", "Wiegand"],
        grauIP: "IP66",
        freq: 13.56,
        rede: ["Ethernet"],
        fornecedor: "ZKteco"
    },
    {
        nome: "SS 320",
        tipo: "controlador",
        capacidade: 30000,
        auth: ["Tag", "Biometria"],
        com: ["RS 485", "Wiegand"],
        grauIP: "N/A",
        freq: 125,
        rede: ["Ethernet"],
        fornecedor: "ZKteco"
    },
    {
        nome: "SS 410",
        tipo: "controlador",
        capacidade: 30000,
        auth: ["Tag", "Biometria", "Senha"],
        com: ["RS 485", "Wiegand", "RS232"],
        grauIP: "N/A",
        freq: 125,
        rede: ["Ethernet"],
        fornecedor: "ZKteco"
    },
    {
        nome: "SS 411 E",
        tipo: "controlador",
        capacidade: 10000,
        auth: ["Tag", "Biometria", "Senha"],
        com: ["RS 485", "Wiegand"],
        grauIP: "N/A",
        freq: 125,
        rede: ["Ethernet"],
        fornecedor: "ZKteco"
    },
    {
        nome: "SS 420",
        tipo: "controlador",
        capacidade: 5000,
        auth: ["Tag", "Biometria", "Senha"],
        com: ["RS 485", "Wiegand"],
        grauIP: "N/A",
        freq: 125,
        rede: ["Ethernet"],
        fornecedor: "ZKteco"
    },
    {
        nome: "SS 610",
        tipo: "controlador",
        capacidade: 10000,
        auth: ["Tag", "Biometria", "Senha"],
        com: ["RS 485", "Wiegand"],
        grauIP: "N/A",
        freq: 125,
        rede: ["Ethernet"],
        fornecedor: "ZKteco"
    },
    {
        nome: "SS 710",
        tipo: "controlador",
        capacidade: 5000,
        auth: ["Face", "Senha", "Tag", "Biometria"],
        com: ["RS 485", "Wiegand"],
        grauIP: "N/A",
        freq: 125,
        rede: ["Ethernet"],
        fornecedor: "ZKteco"
    },
    {
        nome: "SA 200",
        tipo: "controlador",
        capacidade: 1000,
        auth: ["Tag", "Senha"],
        com: ["N/A"],
        grauIP: "N/A",
        freq: 125,
        rede: ["N/A"],
        fornecedor: "ZKteco"
    },
    {
        nome: "SA 202",
        tipo: "controlador",
        capacidade: 1000,
        auth: ["Tag", "Senha"],
        com: ["N/A"],
        grauIP: "N/A",
        freq: 125,
        rede: ["N/A"],
        fornecedor: "Intelbras"
    },
    {
        nome: "SA 202 Automatiza",
        tipo: "controlador",
        capacidade: 1000,
        auth: ["Tag", "Senha"],
        com: ["N/A"],
        grauIP: "N/A",
        freq: 125,
        rede: ["N/A"],
        fornecedor: "ZKteco"
    },
    {
        nome: "SA 203 MF",
        tipo: "controlador",
        capacidade: 1000,
        auth: ["Tag", "Senha"],
        com: ["Wiegand"],
        grauIP: "N/A",
        freq: 13.56,
        rede: ["N/A"],
        fornecedor: "Intelbras"
    },
    {
        nome: "SA 210",
        tipo: "controlador",
        capacidade: 1000,
        auth: ["Tag", "Senha"],
com: ["N/A"],
grauIP: "IP65",
freq: 125,
rede: ["N/A"],
fornecedor: "ZKteco"
},
{
nome: "SA 211 MF",
tipo: "controlador",
capacidade: 1000,
auth: ["Tag", "Senha"],
com: ["Wiegand"],
grauIP: "IP66",
freq: 13.56,
rede: ["N/A"],
fornecedor: "Intelbras"
},
{
nome: "SA 310",
tipo: "controlador",
capacidade: 500,
auth: ["Tag", "Senha", "Biometria"],
com: ["N/A"],
grauIP: "N/A",
freq: 125,
rede: ["N/A"],
fornecedor: "ZKteco"
},
{
nome: "Defense Lite",
tipo: "software",
capacidade: 5000,
auth: ["N/A"],
com: ["IP"],
grauIP: "N/A",
freq: "N/A",
rede: ["Todas"],
fornecedor: "Intelbras"
},
{
nome: "InControl",
tipo: "software",
capacidade: 20000,
auth: ["N/A"],
com: ["IP"],
grauIP: "N/A",
freq: "N/A",
rede: ["LAN"],
fornecedor: "Intelbras"
},
{
nome: "SoapAdmin",
tipo: "software",
capacidade: "N/A",
auth: ["N/A"],
com: ["IP"],
grauIP: "N/A",
freq: "N/A",
rede: ["LAN"],
fornecedor: "ZKteco"
},
{
nome: "SoapAdmin 2.4",
tipo: "software",
capacidade: "N/A",
auth: ["N/A"],
com: ["IP"],
grauIP: "N/A",
freq: "N/A",
rede: ["N/A"],
fornecedor: "ZKteco"
},
{
nome: "SGA 1000 IP",
tipo: "software",
capacidade: 4000,
auth: ["N/A"],
com: ["IP"],
grauIP: "N/A",
freq: "N/A",
rede: ["LAN"],
fornecedor: "Intelbras"
},
{
nome: "SGA 1000",
tipo: "software",
capacidade: 4000,
auth: ["N/A"],
com: ["USB"],
grauIP: "N/A",
freq: "N/A",
rede: ["N/A"],
fornecedor: "Intelbras"
},
{
nome: "CT 500 2pb",
tipo: "controlador",
capacidade: 30000,
auth: ["N/A"],
com: ["RS 485", "Wiegand"],
grauIP: "N/A",
freq: "N/A",
rede: ["Ethernet"],
fornecedor: "ZKteco"
},
{
nome: "CT 3000 2pb",
tipo: "controlador",
capacidade: 100000,
auth: ["N/A"],
com: ["RS 485", "Wiegand"],
grauIP: "N/A",
freq: "N/A",
rede: ["Ethernet"],
fornecedor: "Dahua"
},
{
nome: "MIP 1000 IP",
tipo: "controlador",
capacidade: 4000,
auth: ["N/A"],
com: ["RS 485"],
grauIP: "N/A",
freq: [13.56, 125],
rede: ["Ethernet"],
fornecedor: "Intelbras"
},
{
nome: "MIP 1000",
tipo: "controlador",
capacidade: 4000,
auth: ["N/A"],
com: ["RS 485"],
grauIP: "N/A",
freq: [13.56, 125],
rede: ["N/A"],
fornecedor: "Intelbras"
}
];
